import 'package:flutter/material.dart';
import '../home/home_screen.dart';
import 'register_screen.dart';
import 'forgot_password_screen.dart';

class LoginScreen extends StatefulWidget{final VoidCallback onThemeToggle;const LoginScreen({required this.onThemeToggle,super.key});@override State<LoginScreen> createState()=>_LoginScreenState();}
class _LoginScreenState extends State<LoginScreen>{final email=TextEditingController(text:'farmer@agrismart.app');final pass=TextEditingController(text:'password123');bool hide=true;bool remember=true;
void login(){if(email.text.contains('@')&&pass.text.length>=6)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>HomeScreen(onThemeToggle:widget.onThemeToggle)));else ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid email and password.')));}
@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:460),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.agriculture_rounded,color:Colors.green,size:52),const SizedBox(height:24),Text('Welcome back',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Sign in to continue managing your farm.'),const SizedBox(height:28),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Email',hintText:'you@example.com',prefixIcon:Icon(Icons.email_outlined))),const SizedBox(height:14),TextField(controller:pass,obscureText:hide,decoration:InputDecoration(labelText:'Password',prefixIcon:const Icon(Icons.lock_outline),suffixIcon:IconButton(onPressed:()=>setState(()=>hide=!hide),icon:Icon(hide?Icons.visibility_outlined:Icons.visibility_off_outlined)))),Row(children:[Checkbox(value:remember,onChanged:(v)=>setState(()=>remember=v??false)),const Text('Remember me'),const Spacer(),TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ForgotPasswordScreen())),child:const Text('Forgot password?'))]),const SizedBox(height:10),SizedBox(width:double.infinity,child:FilledButton(onPressed:login,child:const Padding(padding:EdgeInsets.all(14),child:Text('Sign in')))),const SizedBox(height:12),SizedBox(width:double.infinity,child:OutlinedButton.icon(onPressed:login,icon:const Icon(Icons.g_mobiledata,size:28),label:const Text('Continue with Google'))),const SizedBox(height:22),Center(child:TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RegisterScreen(onThemeToggle:widget.onThemeToggle))),child:const Text('New to AgriSmart? Create account'))]))))));}
}
