from pathlib import Path
import joblib
import numpy as np
import pandas as pd
import base64
import io
from PIL import Image
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

BASE = Path(__file__).resolve().parent
MODELS = BASE / "models"
DATA = BASE / "data"
MODELS.mkdir(exist_ok=True)
DATA.mkdir(exist_ok=True)

app = FastAPI(title="AgriSmart ML Service", version="1.2.0")


class DiseaseRequest(BaseModel):
    image_base64: str = Field(..., min_length=1)


class CropRequest(BaseModel):
    nitrogen: float = Field(..., ge=0)
    phosphorus: float = Field(..., ge=0)
    potassium: float = Field(..., ge=0)
    temperature: float
    humidity: float = Field(..., ge=0, le=100)
    ph: float = Field(..., ge=0, le=14)
    rainfall: float = Field(..., ge=0)
    soil_type: str | None = None
    season: str | None = None
    location: str | None = None


class FertilizerRequest(BaseModel):
    temperature: float
    humidity: float = Field(..., ge=0, le=100)
    moisture: float = Field(..., ge=0, le=100)
    soil_type: str
    crop_type: str
    nitrogen: float = Field(..., ge=0)
    potassium: float = Field(..., ge=0)
    phosphorous: float = Field(..., ge=0)


def crop_model():
    model_path = MODELS / "crop_model.joblib"
    if not model_path.exists():
        from train_crop import train_crop_model
        train_crop_model(model_path)
    return joblib.load(model_path)


@app.get("/health")
def health():
    return {
        "success": True,
        "service": "AgriSmart ML",
        "version": "1.2.0",
        "data_source": "bundled_local_data",
    }


@app.post("/api/v1/crop-recommendation")
def crop_recommendation(req: CropRequest):
    model = crop_model()
    x = np.array([[
        req.nitrogen, req.phosphorus, req.potassium,
        req.temperature, req.humidity, req.ph, req.rainfall
    ]], dtype=float)
    crop = str(model.predict(x)[0])
    confidence = float(np.max(model.predict_proba(x)[0])) if hasattr(model, "predict_proba") else 0.0
    return {
        "success": True,
        "crop": crop,
        "confidence": round(confidence, 4),
        "reason": "Prediction generated by the locally trained AgriSmart crop classifier.",
    }


@app.post("/api/v1/fertilizer-recommendation")
def fertilizer_recommendation(req: FertilizerRequest):
    model_path = MODELS / "fertilizer_model.joblib"
    if not model_path.exists():
        from train_fertilizer import train_fertilizer_model
        train_fertilizer_model(model_path)
    model = joblib.load(model_path)
    x = pd.DataFrame([{
        "Temparature": req.temperature,
        "Humidity": req.humidity,
        "Moisture": req.moisture,
        "Soil_Type": req.soil_type,
        "Crop_Type": req.crop_type,
        "Nitrogen": req.nitrogen,
        "Potassium": req.potassium,
        "Phosphorous": req.phosphorous,
    }])
    prediction = str(model.predict(x)[0])
    confidence = float(np.max(model.predict_proba(x)[0])) if hasattr(model, "predict_proba") else 0.0
    return {
        "success": True,
        "fertilizer": prediction,
        "confidence": round(confidence, 4),
    }


class PestRiskRequest(BaseModel):
    crop: str
    pest: str
    temperature_c: float
    humidity_pct: float = Field(..., ge=0, le=100)
    rainfall_mm: float = Field(..., ge=0)
    soil_moisture_pct: float = Field(..., ge=0, le=100)
    pest_count: float = Field(..., ge=0)
    etl: float = Field(..., gt=0)


class YieldRequest(BaseModel):
    crop: str
    crop_year: int = Field(..., ge=1990, le=2100)
    season: str
    state: str
    area: float = Field(..., gt=0)
    annual_rainfall: float = Field(..., ge=0)
    fertilizer: float = Field(..., ge=0)
    pesticide: float = Field(..., ge=0)


@app.post("/api/v1/yield-prediction")
def yield_prediction(req: YieldRequest):
    model_path = MODELS / "yield_model.joblib"
    if not model_path.exists():
        from train_yield import train_yield_model
        train_yield_model(model_path)
    model = joblib.load(model_path)
    x = pd.DataFrame([{
        "Crop": req.crop,
        "Crop_Year": req.crop_year,
        "Season": req.season,
        "State": req.state,
        "Area": req.area,
        "Annual_Rainfall": req.annual_rainfall,
        "Fertilizer": req.fertilizer,
        "Pesticide": req.pesticide,
    }])
    prediction = float(model.predict(x)[0])
    return {
        "success": True,
        "predicted_yield": round(prediction, 6),
        "unit": "dataset-defined",
        "dataset_type": "synthetic_development_data",
        "warning": "Development model only; replace with validated real field data before agronomic use.",
    }


@app.post("/api/v1/disease-detection")
def disease_detection(req: DiseaseRequest):
    model_path = MODELS / "disease_model.joblib"
    if not model_path.exists():
        from train_disease import train_disease_model
        train_disease_model(model_path)
    try:
        raw = base64.b64decode(req.image_base64, validate=True)
        image = Image.open(io.BytesIO(raw)).convert("RGB").resize((64, 64))
    except Exception as exc:
        raise HTTPException(400, f"Invalid image_base64: {exc}") from exc
    x = np.asarray(image, dtype=np.float32).reshape(1, -1) / 255.0
    model = joblib.load(model_path)
    prediction = str(model.predict(x)[0])
    confidence = float(np.max(model.predict_proba(x)[0]))
    return {
        "success": True,
        "disease": prediction,
        "confidence": round(confidence, 4),
        "dataset_type": "synthetic_development_images",
        "warning": "Development classifier only; replace with validated real plant images before agricultural use.",
    }


@app.post("/api/v1/pest-risk")
def pest_risk(req: PestRiskRequest):
    model_path = MODELS / "pest_model.joblib"
    if not model_path.exists():
        from train_pest import train_pest_model
        train_pest_model(model_path)
    model = joblib.load(model_path)
    x = pd.DataFrame([req.model_dump()])
    prediction = str(model.predict(x)[0])
    confidence = float(np.max(model.predict_proba(x)[0])) if hasattr(model, "predict_proba") else 0.0
    return {
        "success": True,
        "risk": prediction,
        "confidence": round(confidence, 4),
        "dataset_type": "synthetic_etl_derived",
        "warning": "Development model only; replace with validated field data before agronomic use.",
    }


@app.get("/api/v1/models")
def models():
    return {
        "success": True,
        "models": {
            "crop": (MODELS / "crop_model.joblib").exists(),
            "fertilizer": (MODELS / "fertilizer_model.joblib").exists(),
            "yield": (MODELS / "yield_model.joblib").exists(),
            "pest_risk": (MODELS / "pest_model.joblib").exists(),
            "disease": (MODELS / "disease_model.joblib").exists(),
        },
    }
