import os
from pathlib import Path
import joblib
import numpy as np
import pandas as pd
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
BASE=Path(__file__).resolve().parent
MODELS=BASE/"models"; DATA=BASE/"data"
MODELS.mkdir(exist_ok=True); DATA.mkdir(exist_ok=True)
app=FastAPI(title="AgriSmart ML API",version="1.0.0")
CROP_URL=os.getenv("CROP_DATASET_URL","https://raw.githubusercontent.com/the-amazing-atharva/Crop-Recommendation/main/Crop_recommendation.csv")
class CropRequest(BaseModel):
    nitrogen: float=Field(...,ge=0); phosphorus: float=Field(...,ge=0); potassium: float=Field(...,ge=0)
    temperature: float; humidity: float=Field(...,ge=0,le=100); ph: float=Field(...,ge=0,le=14); rainfall: float=Field(...,ge=0)
    soil_type: str|None=None; season: str|None=None; location: str|None=None
def crop_model():
    p=MODELS/"crop_model.joblib"
    if not p.exists():
        from train_crop import train_crop_model
        train_crop_model(CROP_URL,p)
    return joblib.load(p)
@app.get("/health")
def health(): return {"success":True,"service":"AgriSmart ML","version":"1.0.0"}
@app.post("/api/v1/crop-recommendation")
def crop_recommendation(req:CropRequest):
    model=crop_model()
    x=np.array([[req.nitrogen,req.phosphorus,req.potassium,req.temperature,req.humidity,req.ph,req.rainfall]],dtype=float)
    crop=str(model.predict(x)[0])
    conf=float(np.max(model.predict_proba(x)[0])) if hasattr(model,"predict_proba") else 0.0
    return {"success":True,"crop":crop,"confidence":round(conf,4),"reason":"Prediction generated by the trained AgriSmart crop classifier."}
@app.post("/api/v1/fertilizer-recommendation")
def fertilizer_recommendation(payload:dict):
    p=MODELS/"fertilizer_model.joblib"
    if not p.exists(): raise HTTPException(503,"Fertilizer model is not trained yet.")
    model=joblib.load(p); x=pd.DataFrame([payload])
    pred=model.predict(x)[0]; conf=float(np.max(model.predict_proba(x)[0])) if hasattr(model,"predict_proba") else 0.0
    return {"success":True,"fertilizer":str(pred),"confidence":round(conf,4)}
@app.post("/api/v1/yield-prediction")
def yield_prediction(payload:dict):
    p=MODELS/"yield_model.joblib"
    if not p.exists(): raise HTTPException(503,"Yield model is not trained yet.")
    model=joblib.load(p); pred=float(model.predict(pd.DataFrame([payload]))[0])
    return {"success":True,"predicted_yield":pred,"unit":"dataset-defined"}
@app.post("/api/v1/pest-risk")
def pest_risk(payload:dict):
    p=MODELS/"pest_model.joblib"
    if not p.exists(): raise HTTPException(503,"Pest-risk model is not trained yet.")
    model=joblib.load(p); x=pd.DataFrame([payload]); pred=str(model.predict(x)[0])
    conf=float(np.max(model.predict_proba(x)[0])) if hasattr(model,"predict_proba") else 0.0
    return {"success":True,"risk":pred,"confidence":round(conf,4)}
@app.get("/api/v1/models")
def models():
    return {"success":True,"models":{"crop":(MODELS/"crop_model.joblib").exists(),"fertilizer":(MODELS/"fertilizer_model.joblib").exists(),"yield":(MODELS/"yield_model.joblib").exists(),"pest_risk":(MODELS/"pest_model.joblib").exists(),"disease":(MODELS/"disease_model.tflite").exists()}}
