import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../services/ml_api_service.dart';

class PestRiskScreen extends StatefulWidget { const PestRiskScreen({super.key}); @override State<PestRiskScreen> createState()=>_PestRiskScreenState(); }
class _PestRiskScreenState extends State<PestRiskScreen>{
 final f=GlobalKey<FormState>(); final temp=TextEditingController(text:'28'),hum=TextEditingController(text:'70'),rain=TextEditingController(text:'20'),soil=TextEditingController(text:'45'),count=TextEditingController(text:'5'),etl=TextEditingController(text:'5'); String crop='Cotton',pest='Jassid'; bool loading=false; String? result,error;
 @override void dispose(){for(final c in [temp,hum,rain,soil,count,etl])c.dispose();super.dispose();} double num(TextEditingController c)=>double.parse(c.text);
 Future<void> submit() async{if(!f.currentState!.validate())return;setState(()=>{loading=true,error=null,result=null});try{final r=await MlApiService.pestRisk(crop:crop,pest:pest,temperatureC:num(temp),humidityPct:num(hum),rainfallMm:num(rain),soilMoisturePct:num(soil),pestCount:num(count),etl:num(etl));if(mounted)setState(()=>result=(r['risk_level']??r['risk']??'Result returned').toString());}catch(e){if(mounted)setState(()=>error=e.toString().replaceFirst('Exception: ',''));}finally{if(mounted)setState(()=>loading=false);}}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Pest Risk')),body:Form(key:f,child:ListView(padding:const EdgeInsets.all(18),children:[_box('Enter current field conditions and pest observations. The configured ML service returns the risk classification.'),_drop('Crop',crop,['Cotton','Rice','Wheat','Maize','Chickpea','Groundnut'],(v)=>setState(()=>crop=v)),_drop('Pest',pest,['Jassid','Whitefly','Thrips','Aphid','Bollworm'],(v)=>setState(()=>pest=v)),_field(temp,'Temperature'),_field(hum,'Humidity'),_field(rain,'Rainfall'),_field(soil,'Soil moisture'),_field(count,'Pest count'),_field(etl,'Economic threshold level (ETL)'),FilledButton.icon(onPressed:loading?null:submit,icon:const Icon(Icons.bug_report),label:Text(loading?'Checking…':'Check Pest Risk')),if(error!=null)_msg(c,error!,true),if(result!=null)_msg(c,'Risk: $result',false)])));
 Widget _field(TextEditingController c,String l)=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:l),validator:(v)=>double.tryParse(v??'')==null?'Enter a valid number':null));
 Widget _drop(String l,String v,List<String> items,ValueChanged<String> cb)=>Padding(padding:const EdgeInsets.only(bottom:12),child:DropdownButtonFormField<String>(value:v,decoration:InputDecoration(labelText:l),items:items.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>cb(x!)));
 Widget _box(String s)=>Container(margin:const EdgeInsets.only(bottom:16),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:AppTheme.lightGreen,borderRadius:BorderRadius.circular(18)),child:Text(s,style:const TextStyle(fontWeight:FontWeight.w700)));
 Widget _msg(BuildContext c,String s,bool e)=>Container(margin:const EdgeInsets.only(top:16),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:e?Theme.of(c).colorScheme.errorContainer:AppTheme.lightGreen,borderRadius:BorderRadius.circular(16)),child:Text(s,style:const TextStyle(fontWeight:FontWeight.w700)));
}
